### ISSUE TITLE
Consul 1.0.0 / Consul Api(jar) 1.2.4 wrong http method for agentCheckPass

### ISSUE THREAD

**Issue by radut** [Ecwid/consul-api#135]
AgentConsulClient should make a PUT instead of GET

I have tried curl with PUT and it worked

consul log:

    2017/11/14 13:00:10 [ERR] http: Request GET /v1/agent/check/pass/service:spring-mvc-archetype-f97384782ff84dd3dc86fb6ca95dc939, error: method GET not allowed from=127.0.0.1:61048
    2017/11/14 13:00:10 [ERR] http: Request GET /v1/agent/check/pass/service:spring-mvc-archetype-585af995-d9c0-49b0-94cf-e7213f5b16f9-management, error: method GET not allowed from=127.0.0.1:61048

java log:

    com.ecwid.consul.v1.OperationException: OperationException(statusCode=405, statusMessage='Method Not Allowed', statusContent='method GET not allowed')
	    at com.ecwid.consul.v1.agent.AgentConsulClient.agentCheckPass(AgentConsulClient.java:197) ~[consul-api-1.2.4.jar:?]
	    at com.ecwid.consul.v1.agent.AgentConsulClient.agentCheckPass(AgentConsulClient.java:186) ~[consul-api-1.2.4.jar:?]
	    at com.ecwid.consul.v1.ConsulClient.agentCheckPass(ConsulClient.java:247) ~[consul-api-1.2.4.jar:?]
	    at org.springframework.cloud.consul.discovery.TtlScheduler$ConsulHeartbeatTask.run(TtlScheduler.java:91) ~[spring-cloud-consul-discovery-1.2.1.RELEASE.jar:1.2.1.RELEASE]
	    at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.3.10.RELEASE.jar:4.3.10.RELEASE]
	    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_144]
	    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_144]
	    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_144]
	    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_144]
	    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_144]
	    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_144]
	    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]

source: 

     @Override
	 public Response<Void> agentCheckPass(String checkId, String note) {
		UrlParameters noteParams = note != null ? new SingleUrlParameters("note", note) : null;
		RawResponse rawResponse = rawClient.makeGetRequest("/v1/agent/check/pass/" + checkId, noteParams);

		if (rawResponse.getStatusCode() == 200) {
			return new Response<Void>(null, rawResponse);
		} else {
			throw new OperationException(rawResponse);
		}
	}

**Comment by radut** [comment]
GET 

    curl -X GET "http://localhost:8500/v1/agent/check/pass/service:spring-mvc-archetype-71468e103854d7cc60a93826d824b19f?token=${TOKEN}"
    method GET not allowed

PUT

    radut@radut ~ $ curl -X PUT "http://localhost:8500/v1/agent/check/pass/service:spring-mvc-archetype-71468e103854d7cc60a93826d824b19f?token=${TOKEN}"

    radut@radut ~ $

**Comment by radut** [comment]
same for deregister

     2017/11/14 20:49:58 [ERR] http: Request GET /v1/agent/service/deregister/spring-mvc-archetype-e78942ffe16af3f2a2ed208ffbc488d4, error: method GET not allowed from=127.0.0.1:60138

**Comment by spencergibb** [comment]
I think this will be taken care of by #134

**Comment by leiy88** [comment]
I have the same issue.

**Comment by leiy88** [comment]
However, the issure is still remain.

**Comment by vgv** [comment]
I've merged the #134
