### ISSUE TITLE
Problem while getting value from KV Store

### ISSUE THREAD

**Issue by tugbabodrumlu** [Ecwid/consul-api#42]
While using the client to get a value from KV Store we get the following exception:
```
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 1 column 92
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:176)
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40)
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:81)
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:60)
        at com.google.gson.Gson.fromJson(Gson.java:803)
        at com.google.gson.Gson.fromJson(Gson.java:768)
        at com.google.gson.Gson.fromJson(Gson.java:717)
        at com.ecwid.consul.v1.kv.KeyValueConsulClient.getKVBinaryValue(KeyValueConsulClient.java:114)
        at com.ecwid.consul.v1.kv.KeyValueConsulClient.getKVBinaryValue(KeyValueConsulClient.java:105)
        at com.ecwid.consul.v1.kv.KeyValueConsulClient.getKVBinaryValue(KeyValueConsulClient.java:95)
        at com.ecwid.consul.v1.ConsulClient.getKVBinaryValue(ConsulClient.java:364)
        at
``` 
The entry in column 92 starts with rO0AB  (e.g."Value":"rO0AB...")

**Comment by vgv** [comment]
It seems that you try to get base64 value by "binary" method.

consul-api contains two "method sets" for KV:
* getKVValue / setKVValue
* getKVBinaryValue / setKVBinaryValue

A few examples:
setKVValue("key", "Hello world") 
getKVValue("key")  => SGVsbG8gd29ybGQ=    (base64 of "Hello world" string)

setKVBinaryValue("otherKey", new byte[] {1,2,3,4,5})
getKVBinaryValue("otherKey") =>  {1,2,3,4,5}


So, if you want to get/set the same value and do not want to deal with base64 - please, use "Binary" methods
