### ISSUE TITLE
TLS Config Example.

### ISSUE THREAD

**Issue by javieriturra** [Ecwid/consul-api#86]
Could you provide an example with TLSConfig?

Trying to run this code:

        TLSConfig tlsConfig = new TLSConfig(TLSConfig.KeyStoreInstanceType.JKS, "./ssl/truststore.jks", "123456", "./ssl/keystore.jks", "123456", 18501);
        final ConsulClient consulClient = new ConsulClient("https://localhost", tlsConfig);
        consulClient.setKVValue("spike/config/bar", "1");
        final Response<GetValue> kvValue = consulClient.getKVValue("spike/config/bar");
        System.out.println(kvValue.getValue().getDecodedValue());

And I get this:

Exception in thread "main" java.lang.UnsupportedOperationException
	at org.apache.http.impl.client.InternalHttpClient$1.getSchemeRegistry(InternalHttpClient.java:238)
	at com.ecwid.consul.transport.DefaultHttpsTransport.<init>(DefaultHttpsTransport.java:57)
	at com.ecwid.consul.v1.ConsulRawClient.<init>(ConsulRawClient.java:60)
	at com.ecwid.consul.v1.ConsulRawClient.<init>(ConsulRawClient.java:40)
	at com.ecwid.consul.v1.ConsulClient.<init>(ConsulClient.java:121)
	at cl.tidchile.mamut.consul.spike.JavaSSLDemoApp.main(JavaSSLDemoApp.java:13)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)

Thank you in advance.

**Comment by javahas** [comment]
hi
Did you find any workaround for this issue?

**Comment by newmodelcoder** [comment]
Just wanted to add a note here that using TLSConfig is not the only way to enable TLS with the Consul client.   It's also possible to rely on system properties to configure the trust store (and presumably key store, but I haven't tried that yet).  Then including the `https` scheme in the consul host value did the trick.  

More details in https://github.com/Ecwid/consul-api/issues/129
