### ISSUE TITLE
aclCreate Invalid ACL Type

### ISSUE THREAD

**Issue by bomee** [Ecwid/consul-api#92]
consul server not support uppercase acl type by CLIENT
```
OperationException{statusCode=500, statusMessage='Internal Server Error', statusContent='Invalid ACL Type'}
	at com.ecwid.consul.v1.acl.AclConsulClient.aclCreate(AclConsulClient.java:66)
	at com.ecwid.consul.v1.ConsulClient.aclCreate(ConsulClient.java:154)
```

**Comment by hi-sb** [comment]
I have the same problem as you have. The correct enumeration type should be lowercase. After I modify this enumeration class, I override the.Jar in the local Maven to resolve it.

```
//
// Source code recreated from a .class file by IntelliJ IDEA
// (powered by Fernflower decompiler)
//

package com.ecwid.consul.v1.acl.model;

public enum AclType {
    client,
    management;

    private AclType() {
    }
}

```
